---
- name: 'Check mandatory variables are defined'
  assert:
    that:
      - application_name is defined
      - graphs_path is defined
      - xml_file is defined

- name: Create app container
  docker_container:
    name: "{{ application_name }}"
    image: "namelivia/{{ application_name }}:latest"
    pull: true
    cleanup: true
    memory: "200MB"
    log_driver: "loki"
    log_options:
      loki-url: "{{ loki_url }}"
      loki-batch-size: "400"
    env:
      GRAPHS_PATH: "{{ graphs_path }}"
      XML_FILE: "{{ xml_file }}"
